
export const themes= {
    'vintage-garden-primary': '#2D4659',
    'vintage-garden-background': '#FDFBDA',
    'vintage-garden-accent': '#819F7F',
    'cosmic-symphony-primary': '#F0EB8D',
    'cosmic-symphony-background': '#413543',
    'cosmic-symphony-accent': '#8F43EE',
    'rustic-charm-primary': '#EA5455',
    'rustic-charm-background': '#F9F5EB',
    'rustic-charm-accent': '#E4BD7D',
    'sunset-serenade-primary': '#210062',
    'sunset-serenade-background': '#009FBD',
    'sunset-serenade-accent': '#77037B',
    'industrial-chic-primary': '#F45050',
    'industrial-chic-background': '#F0F0F0',
    'industrial-chic-accent': '#F9D949',
    'blackout-neutrals-primary': '#F3EFE0',
    'blackout-neutrals-background': '#222222',
    'blackout-neutrals-accent': '#22A39F',
    'vibrant-spectrum-primary': '#4A0E5C',
    'vibrant-spectrum-background': '#CCF0C3',
    'vibrant-spectrum-accent': '#BCA3CA',
    'coastal-sunrise-primary': '#005874',
    'coastal-sunrise-background': '#E6E6D4',
    'coastal-sunrise-accent': '#FFBE00',
    'oceanic-serenity-primary': '#CBE4DE',
    'oceanic-serenity-background': '#2C3333',
    'oceanic-serenity-accent': '#2E4F4F',
  }