export const THEMES = [
  {
    name: "Vintage Garden",
    value: "vintageGarden",
    primary: "#2D4659",
    background: "#FDFBDA",
    accent: "#819F7F",
  },
  {
    name: "Cosmic Symphony",
    value: "cosmicSymphony",
    primary: "#F0EB8D",
    background: "#413543",
    accent: "#8F43EE",
  },
  {
    name: "Rustic Charm",
    value: "rusticCharm",
    primary: "#EA5455",
    background: "#F9F5EB",
    accent: "#E4BD7D",
  },
  {
    name: "Sunset Serenade",
    value: "sunsetSerenade",
    primary: "#210062",
    background: "#009FBD",
    accent: "#77037B",
  },
  {
    name: "Industrial Chic",
    value: "industrialChic",
    primary: "#F45050",
    background: "#F0F0F0",
    accent: "#F9D949",
  },
  {
    name: "Blackout Neutrals",
    value: "blackoutNeutrals",
    primary: "#F3EFE0",
    background: "#222222",
    accent: "#22A39F",
  },
  {
    name: "Vibrant Spectrum",
    value: "vibrantSpectrum",
    primary: "#4A0E5C",
    background: "#CCF0C3",
    accent: "#BCA3CA",
  },
  {
    name: "Coastal Sunrise",
    value: "coastalSunrise",
    primary: "#005874",
    background: "#E6E6D4",
    accent: "#FFBE00",
  },
  {
    name: "Oceanic Serenity",
    value: "oceanicSerenity",
    primary: "#CBE4DE",
    background: "#2C3333",
    accent: "#2E4F4F",
  },
];

export const THEME = [
  "vintageGarden",
  "cosmicSymphony",
  "rusticCharm",
  "sunsetSerenade",
  "industrialChic",
  "blackoutNeutrals",
  "vibrantSpectrum",
  "coastalSunrise",
  "oceanicSerenity",
];
